DROP TABLE IF EXISTS Movie;

DROP TABLE IF EXISTS Person;

DROP TABLE IF EXISTS Genre;

DROP TABLE IF EXISTS Keyword;

DROP TABLE IF EXISTS DirectedBy;

DROP TABLE IF EXISTS Starring;

DROP TABLE IF EXISTS ShootingLocation;
