<!-- Inserts into database -->
<?php

//Open a connection to dbase server
include 'open.php';

//Prepare a statement to be executed later,
if ($stmt = $conn->prepare("CALL deleteRole(?, ?, ?)")) {

    //Bind a variable to the missing data value denoted by ? above
    $stmt->bind_param("sss", $MovieID, $PersonID, $Role);
        
    //Set the value of the bound variable
    $MovieID = $_POST['MovieID'];
	$PersonID = $_POST['PersonID'];
	$Role = $_POST['Role'];
    
    //Execute the statement on dbase
    if (!empty($MovieID) && !empty($PersonID) && !empty($Role)) {
   	    if ($stmt->execute()) {

      	//Store result set generated by the prepared statement
        $result = $stmt->get_result();

		if ($result->num_rows != 0) {
			//Get error messages
			foreach($result as $row){
				echo $row["errorMessage"];
			 }
		} else {
			echo "Succesfully removed!";
		}
        
		//Free the result set returned from the query, since we've stored data in array
        $result->free_result();
    	} else {
			echo "We could not execute this insertion. Please make sure your inputs are valid";
		}
    } else {
	    echo "You are missing an input value.";
    }
}

//Close the prepared statement
$stmt->close();

//Close the connection opened by open.php since we no longer need access to dbase
$conn->close();
?>