<!-- Returns trends of a genre (film production output and distribution of overall films over time) -->
<?php

//Open a connection to dbase server
include 'open.php';

//Construct an array in which we'll store our data
$dataPoints = array();
$dataPoints2 = array();

//Prepare a statement to be executed later,
if ($stmt = $conn->prepare("CALL GenreTrends(?)")) {

    //Bind a variable to the missing data value denoted by ? above
    $stmt->bind_param("s", $Genre);
        
    //Set the value of the bound variable
    $Genre = $_POST['Genre'];
    
    //Execute the statement on dbase
    if (!empty($Genre)) {
   	    if ($stmt->execute()) {

      	//Store result set generated by the prepared statement
        $result = $stmt->get_result();

        //Get each row of result set and push it into array
	    foreach($result as $row){
            array_push($dataPoints, array( "label"=> $row["decade"],
			"y"=> $row["numFilms"]));
			array_push($dataPoints2, array( "label"=> $row["decade"],
			"y"=> $row["Percentage"]));
        }
        
		//Free the result set returned from the query, since we've stored data in array
        $result->free_result();
    	} else {
			echo "Please make sure your input is valid.";
		}
    } else {
	    echo "Please input a genre.";
    }
}

//Close the prepared statement
$stmt->close();

//Close the connection opened by open.php since we no longer need access to dbase
$conn->close();
?>
	<html>

	<body>
		<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
		<div id="chartContainer1" style="height: 300px; width: 100%;"></div>
		<div id="chartContainer2" style="height: 300px; width: 100%;"></div>

		<script type="text/javascript">
			window.onload = function() {
				var chart1 = new CanvasJS.Chart("chartContainer1", {
					animationEnabled: true,
					theme: "dark1", // "light1", "light2", "dark1", "dark2"
					title: {
						text: "Trends in genre production output over time"
					},
					axisX: {
						title: "Decade"
					},
					axisY: {
						title: "Number of films"
					},
					data: [{
						type: "line",
						indexLabelFontSize: 16,
						//json_encode function called below transforms numeric strings into numbers
						dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
					}]
				});
	
				var chart2 = new CanvasJS.Chart("chartContainer2", {
					animationEnabled: true,
					theme: "dark1", // "light1", "light2", "dark1", "dark2"
					title: {
						text: "Trends in genre distribution over time"
					},
					axisX: {
						title: "Decade"
					},
					axisY: {
						title: "% of total films released"
					},
					data: [{
						type: "line",
						indexLabelFontSize: 16,
						//json_encode function called below transforms numeric strings into numbers
						dataPoints: <?php echo json_encode($dataPoints2, JSON_NUMERIC_CHECK); ?>
					}]
				});
				chart1.render();
				chart2.render();
			}
			</script>
	</body>

	</html>