<!-- Returns list of films release between a range of years -->
<?php

//Open a connection to dbase server
include 'open.php';



//Prepare a statement to be executed later,
if ($stmt = $conn->prepare("CALL FilmsYearRange(?, ?)")) {

    //Bind variables to the missing data value denoted by ? above
    $stmt->bind_param("ii", $startYear, $endYear);
        
    //Set the value of the bound variables
    $startYear = $_POST['startYear'];
    $endYear = $_POST['endYear'];

    
    //Execute the statement on dbase
    if (!empty($startYear) && !empty($endYear)) {
   	    if ($stmt->execute()) {

      	//Store result set generated by the prepared statement
        $result = $stmt->get_result();

		if ($result->num_rows == 0) {
			echo "No revenue information found for this range of years.";
		} else {

        	//Get each row of result set and push it into table
	    	echo "<table border=\"2px solid black\">";
	    	echo "<tr><td>Title</td><td>Year</td><td>Revenue</td></tr>";
	 		foreach($result as $row){
	    		echo "<tr>";
				echo "<td>".$row["title"]."</td>";
				echo "<td>".$row["year"]."</td>";
				echo "<td>".number_format($row["revenue_adj"], 2)."</td>";
				echo "<tr>";
	    	}
	    	echo "<table>";
		}
        
        
		//Free the result set returned from the query, since we've stored data in array
        $result->free_result();
    	} else {
			echo "Please make sure your input is valid.";
		}
    } else {
	    echo "Please input a start year and end year.";
    }
}

//Close the prepared statement
$stmt->close();

//Close the connection opened by open.php since we no longer need access to dbase
$conn->close();
?>