<!-- Returns top 5 ranked films in a decade -->
<?php

//Open a connection to dbase server
include 'open.php';



//Prepare a statement to be executed later,
if ($stmt = $conn->prepare("CALL GenreRank(?)")) {

    //Bind variables to the missing data value denoted by ? above
    $stmt->bind_param("s", $Genre);
        
    //Set the value of the bound variables
    $Genre = $_POST['Genre'];

    
    //Execute the statement on dbase
    if (!empty($Genre)) {
   	    if ($stmt->execute()) {

      	    //Store result set generated by the prepared statement
            $result = $stmt->get_result();

	        if ($result->num_rows == 0) {
	            echo "There is no ranking information for this genre";
	        } else {
                //Get each row of result set and push it into table
	            echo "<table border=\"2px solid black\">";
	            echo "<tr><td>Title</td><td>Year</td><td>Rank</td></tr>";
	            foreach($result as $row) {
	    	        echo "<tr>";
		            echo "<td>".$row["title"]."</td>";
		            echo "<td>".$row["year"]."</td>";
		            echo "<td>".$row["rank"]."</td>";
		            echo "<tr>";
	            }
	            echo "<table>";
	        }

    	} else {
			echo "Please make sure your input is valid.";
		}
    } else {
	    echo "Please input a genre.";
    }
}

//Close the prepared statement
$stmt->close();

//Close the connection opened by open.php since we no longer need access to dbase
$conn->close();
?>	   