<!-- Returns top 5 highest-grossing films in a genre -->
<?php

//Open a connection to dbase server
include 'open.php';



//Prepare a statement to be executed later,
if ($stmt = $conn->prepare("CALL TopFiveGenre(?)")) {

    //Bind variables to the missing data value denoted by ? above
    $stmt->bind_param("s", $Genre);
        
    //Set the value of the bound variables
    $Genre = $_POST['Genre'];

    
    //Execute the statement on dbase
    if (!empty($Genre)) {
   	    if ($stmt->execute()) {

      	//Store result set generated by the prepared statement
        $result = $stmt->get_result();

	if ($result->num_rows == 0) {
	   echo "no revenue information for this genre";
	} else {
        //Get each row of result set and push it into table
	    echo "<table border=\"2px solid black\">";
	    echo "<tr><td>Title</td><td>Year</td><td>Revenue</td><td>Adjusted_Revenue</td></tr>";
	    foreach($result as $row) {
	    	echo "<tr>";
		echo "<td>".$row["title"]."</td>";
		echo "<td>".$row["year"]."</td>";
		echo "<td>".number_format($row["revenue"], 2)."</td>";
		echo "<td>".number_format($row["revenue_adj"], 2)."</td>";
		echo "<tr>";
	    }
	    echo "<table>";
	}

    	} else {
			echo "Please make sure your input is valid.";
		}
    } else {
	    echo "Please input a genre.";
    }
}

//Close the prepared statement
$stmt->close();

//Close the connection opened by open.php since we no longer need access to dbase
$conn->close();
?>	   