<!-- Returns top 5 highest-grossing films of a given decade -->
<?php

//Open a connection to dbase server
include 'open.php';

//Construct an array in which we'll store our data
$dataPoints = array();

//Prepare a statement to be executed later,
if ($stmt = $conn->prepare("CALL TopFiveDecade(?)")) {

    //Bind variables to the missing data value denoted by ? above
    $stmt->bind_param("s", $Year);
        
    //Set the value of the bound variables
    $Year = $_POST['Year'];
    
    //Execute the statement on dbase
    if (!empty($Year)) {
   	    if ($stmt->execute()) {

      		//Store result set generated by the prepared statement
        	$result = $stmt->get_result();

			if ($result->num_rows == 0) {
	   			echo "no revenue information for this decade";
			} else {
				foreach($result as $row) {
					array_push($dataPoints, array("label"=> $row["title"],
		   			"y"=> $row["revenue_adj"]));
	   			}
			}
		//Free the result set returned from the query, since we've stored data in array
        $result->free_result();
 		} else {
			echo "Please make sure your input is valid.";
		}
    } else {
	    echo "Please input a year.";
    }
}

//Close the prepared statement
$stmt->close();

//Close the connection opened by open.php since we no longer need access to dbase
$conn->close();
?>	   
    
	<html>

	<head>
		<script type="text/javascript">
		window.onload = function() {
			var chart = new CanvasJS.Chart("chartContainer", {
				animationEnabled: true,
				theme: "dark1", // "light1", "light2", "dark1", "dark2"
				title: {
					text: "Top grossing films"
				},
				axisY: {
					title: "Revenue ($)"
				},
				axisX: {
				    interval: 1,
					title: "Film"
				},
				data: [{
					type: "column",
					//json_encode function called below transforms numeric strings into numbers
					dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
				}]
			});
			chart.render();
		}
		</script>
	</head>

	<body>
		<div id="chartContainer" style="height: 300px; width: 100%;"></div>
		<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
	</body>

	</html>